services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: visionary-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./src:/app/src
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge